// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddFriendReq struct {
	UserID uint `json:"user_id"`
}

type AddFriendResp struct {
	Code uint `json:"code"`
}

type DeleteFriendReq struct {
	UserID uint `json:"user_id"`
}

type DeleteFriendResp struct {
	Code uint `json:"code"`
}

type GetFriendInfoReq struct {
	UUID string `path:"uuid"`
}

type GetFriendInfoResp struct {
	Code       uint       `json:"code"`
	FriendInfo FriendInfo `json:"friend_info"`
}

type GetFriendListReq struct {
	Page  uint `form:"page,default=1"`
	Limit uint `form:"limit,default=20"`
}

type GetFriendListResp struct {
	Code uint `json:"code"`
	PageableInfo
	FriendList []CommonUserInfo `json:"friends"`
}
