// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CountUserGroupsReq struct {
}

type CountUserGroupsResp struct {
	Code  uint `json:"code"`
	Total uint `json:"total"`
}

type CreateGroupReq struct {
	GroupName    string `json:"group_name"`
	GroupMembers []uint `json:"members"`
	GroupAvatar  string `json:"avatar"`
}

type CreateGroupResp struct {
	Code        uint   `json:"code"`
	GroupUUID   string `json:"group_uuid"`
	GroupAvatar string `json:"grou_avatar"`
}

type DeleteGroupReq struct {
	GroupID uint `json:"group_id"`
}

type DeleteGroupResp struct {
	Code uint `json:"code"`
}

type GetGroupInfoByUUIDReq struct {
	UUID string `path:"uuid"`
}

type GetGroupInfoByUUIDResp struct {
	Code   uint          `json:"code"`
	Result FullGroupInfo `json:"result"`
}

type GetGroupMembersReq struct {
	GroupID  uint `path:"group_id"`
	Page     uint `form:"page,default=1"`
	Limit    uint `form:"limit,default=20"`
	LatestID uint `form:"lastestId,default=0"`
}

type GetGroupMembersResp struct {
	Code uint `json:"code"`
	PageableInfo
	MemberList []GroupMemberInfo `json:"member_list"`
}

type GetUserGroupReq struct {
	Page     uint `form:"page,default=1"`
	Limit    uint `form:"limit,default=20"`
	LatestID uint `form:"lastestId,default=0"`
}

type GetUserGroupResp struct {
	Code uint `json:"code"`
	PageableInfo
	Groups []GroupInfo `json:"groups"`
}

type JoinGroupReq struct {
	GroupID uint `path:"group_id"`
}

type JoinGroupResp struct {
	Code uint `json:"code"`
}

type LeaveGroupReq struct {
	GroupID uint `path:"group_id"`
}

type LeaveGroupResp struct {
	Code uint `json:"code"`
}

type SearchGroupReq struct {
	Qurey string `form:"query"`
}

type SearchGroupResp struct {
	Code    uint            `json:"code"`
	Results []FullGroupInfo `json:"results"`
}

type UpdateGroupInfoReq struct {
	GroupID   uint   `json:"group_id"`
	GroupName string `json:"group_name"`
	GroupDesc string `json:"group_desc"`
}

type UpdateGroupInfoResp struct {
	Code uint `json:"code"`
}

type UploadGroupAvatarReq struct {
	GroupID uint `path:"group_id"`
}

type UploadGroupAvatarResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}
