// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DeleteMessageReq struct {
	MesssageID uint `json:"msg_id"`
}

type DeleteMessageResp struct {
	Code uint `json:"code"`
}

type GetMessagesReq struct {
	MessageType uint `json:"message_type"`
	SouceId     uint `json:"id"` //can be a groupId or friendId
	Page        uint `form:"page,default=1"`
	Limit       uint `form:"limit,default=20"`
	LatestID    uint `form:"latest_id,default=0"`
}

type GetMessagesResp struct {
	Code     uint          `json:"code"`
	Messages []MessageUser `json:"message"`
}
