// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateStickerGroupReq struct {
	StickerName string `form:"sticker_name"`
}

type CreateStickerGroupResp struct {
	Code             uint   `json:"code"`
	StickerGroupUUID string `json:"sticker_group_id"`
}

type GetStickerInfoReq struct {
	StickerUUID string `path:"sticker_uuid"`
}

type GetStickerInfoResp struct {
	Code        uint        `json:"code"`
	StickerInfo StickerInfo `json:"sticker_info"`
}

type GetStickerListReq struct {
}

type GetStickerListResp struct {
	Code     uint          `json:"code"`
	Stickers []StickerInfo `json:"stickers"`
}

type GetStickerResourcesReq struct {
	StickerGroupUUID string `path:"sticker_group_uuid"`
}

type GetStickerResourcesResp struct {
	Code          uint     `json:"code"`
	StickerID     string   `json:"sticker_id"`
	ResourcesPath []string `json:"resources_path"`
}
