// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddStoryReq struct {
}

type AddStoryResp struct {
	Code uint      `json:"code"`
	Info StoryInfo `json:"story_info"`
}

type CreateStoryLikeReq struct {
	StoryId uint `json:"story_id"`
}

type CreateStoryLikeResp struct {
	Code uint `json:"code"`
}

type DeleteStoryLikeReq struct {
	StoryId uint `json:"story_id"`
}

type DeleteStoryLikeResp struct {
	Code uint `json:"code"`
}

type DeleteStoryReq struct {
	StoryID uint `json:"story_id"`
}

type DeleteStoryResp struct {
	Code uint `json:"code"`
}

type GetActiveStoryReq struct {
	Page             uint `form:"page,default=1"`
	Limit            uint `form:"limit,default=20"`
	LatestID         uint `form:"lastestId,default=0"`
	StoryCreatedTime uint `form:"story_created_time,default=0"`
}

type GetActiveStoryResp struct {
	Code uint `json:"code"`
	PageableInfo
	CurrentStoryTime uint          `json:"current_story_time"`
	FriendStroies    []FriendStroy `json:"active_stories"`
}

type GetStoryInfoByIdRep struct {
	StoryID uint `path:"story_id"`
}

type GetStoryInfoByIdResp struct {
	Code uint `json:"code"`
	StoryInfo
	IsLiked        bool                     `json:"is_liked"`
	TotalSeenCount uint                     `json:"seen_count"`
	CreateAt       uint                     `json:"create_at"`
	StorySeenList  []StorySeenUserBasicInfo `json:"story_seen_list"`
}

type GetStorySeenListReq struct {
	StoryId uint `path:"story_id"`
}

type GetStorySeenListResp struct {
	Code      uint            `json:"code"`
	TotalSeen uint            `json:"total_seen"`
	SeenList  []StorySeenInfo `json:"seen_list"`
}

type GetUserStoryReq struct {
	UserId           uint `path:"user_id"`
	StoryCreatedTime uint `form:"story_created_time,default=0"`
}

type GetUserStoryResp struct {
	Code        uint        `json:"code"`
	Stories     []StoryInfo `json:"stories"`
	LastStoryId uint        `json:"last_story_id"`
}

type UpdateStorySeenReq struct {
	FriendId uint `json:"friend_id"`
	StoryId  uint `json:"story_id"`
}

type UpdateStorySeenResp struct {
	Code uint `json:"code"`
}
