// Code generated by goctl. DO NOT EDIT.
package types

type HealthCheckReq struct {
}

type HealthCheckResp struct {
	Resp string `json:"resp"`
}

type CommonUserInfo struct {
	ID       uint   `json:"id,omitempty"`
	Uuid     string `json:"uuid,omitempty"`
	NickName string `json:"name,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
	Email    string `json:"email,omitempty"`
	Cover    string `json:"cover,omitempty"`
}

type SignUpReq struct {
	Email    string `json:"email" validate:"email,min=8,max=32"`
	Name     string `json:"name" validate:"min=8,max=16"`
	Password string `json:"password" validate:"min=8,max=32"`
}

type SignUpResp struct {
	Code        uint   `json:"code"`
	Token       string `json:"token"`
	ExpiredTime uint   `json:"expired_time"`
}

type SignInReq struct {
	Email    string `json:"email" validate:"email,min=8,max=32"`
	Password string `json:"password" validate:"min=8,max=32"`
}

type SignInResp struct {
	Code        uint           `json:"code"`
	Token       string         `json:"token"`
	ExpiredTime uint           `json:"expired_time"`
	UserInfo    CommonUserInfo `json:"user_info"`
}

type GetUserInfoReq struct {
	UserID uint   `form:"id,optional"`
	UUID   string `form:"uuid,optional"`
}

type GetUserInfoResp struct {
	Code   uint   `json:"code"`
	UUID   string `json:"uuid"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Avatar string `json:"avatar"`
	Cover  string `json:"cover"`
}

type UpdateUserInfoReq struct {
	Name string `json:"name" validate:"min=8,max=32"`
}

type UpdateUserInfoResp struct {
	Code uint `json:"code"`
}

type UploadUserAvatarReq struct {
}

type UploadUserAvatarResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}

type SearchUserReq struct {
	Qurey string `form:"query"`
}

type SearchUserResp struct {
	Code    uint               `json:"code"`
	Results []SearchUserResult `json:"results"`
}

type SearchUserResult struct {
	UserInfo CommonUserInfo `json:"user_info"`
	IsFriend bool           `json:"is_friend"`
}

type AddFriendReq struct {
	UserID uint `json:"user_id"`
}

type AddFriendResp struct {
	Code uint `json:"code"`
}

type DeleteFriendReq struct {
	UserID uint `json:"user_id"`
}

type DeleteFriendResp struct {
	Code uint `json:"code"`
}

type GetFriendListReq struct {
}

type GetFriendListResp struct {
	FriendList []CommonUserInfo `json:"friends"`
}

type CreateGroupReq struct {
	GroupName string `json:"group_name"`
}

type CreateGroupResp struct {
	Code      uint   `json:"code"`
	GroupUUID string `json:"group_uuid"`
}

type JoinGroupReq struct {
	GroupID uint `path:"group_id"`
}

type JoinGroupResp struct {
	Code uint `json:"code"`
}

type LeaveGroupReq struct {
	GroupID uint `path:"group_id"`
}

type LeaveGroupResp struct {
	Code uint `json:"code"`
}

type DeleteGroupReq struct {
	GroupID uint `json:"group_id"`
}

type DeleteGroupResp struct {
	Code uint `json:"code"`
}

type GetGroupMembersReq struct {
	GroupID uint `path:"group_id"`
}

type GetGroupMembersResp struct {
	Code       uint              `json:"code"`
	MemberList []GroupMemberInfo `json:"member_list"`
}

type UpdateGroupInfoReq struct {
	GroupID   uint   `json:"group_id"`
	GroupName string `json:"group_name"`
}

type UpdateGroupInfoResp struct {
	Code uint `json:"code"`
}

type UploadGroupAvatarReq struct {
	GroupID uint `path:"grou_id"`
}

type UploadGroupAvatarResp struct {
	Code uint `json:"code"`
}

type GetUserGroupReq struct {
}

type GetUserGroupResp struct {
	Code   uint        `json:"code"`
	Groups []GroupInfo `json:"groups"`
}

type GroupMemberInfo struct {
	CommonUserInfo
	IsGroupLead bool `json:"is_group_lead"`
}

type GroupInfo struct {
	ID     uint   `json:"id"`
	Uuid   string `json:"uuid"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type SearchGroupInfo struct {
	Info     GroupInfo `json:"group_info"`
	IsJoined bool      `json:"is_joined"`
}

type GetMessagesReq struct {
	ID          uint `json:"id"` //can be a user id or a group id
	MessageType uint `json:"message_type"`
	FriendID    uint `json:"friend_id"` //only for message type = 1
}

type GetMessagesResp struct {
	Code     uint          `json:"code"`
	Messages []MessageUser `json:"message"`
}

type DeleteMessageReq struct {
	MesssageID uint `json:"msg_id"`
}

type DeleteMessageResp struct {
	Code uint `json:"code"`
}

type MessageUser struct {
	MessageID   uint   `json:"id"`
	FromID      uint   `json:"from_id"`
	ToID        uint   `json:"to_id"`
	Content     string `json:"content"`
	ContentType uint   `json:"content_type"`
	MessageType uint   `json:"message_type"`
	CreatedAt   uint   `json:"create_at"`
}

type UploadImageReq struct {
	ImageType string `json:"image_type"`
	Data      string `json:"data"`
}

type UploadImageResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}

type UploadImagesReq struct {
}

type UploadImagesResp struct {
}

type UploadFildReq struct {
	Data     string `json:"data"`
	FileName string `json:"file_name"`
}

type UploadFileResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}

type UploadFilsReq struct {
}

type UploadFilesResp struct {
}

type AddStoryReq struct {
}

type AddStoryResp struct {
	Code    uint `json:"code"`
	StoryID uint `json:"story_id"`
}

type GetUserStoryReq struct {
}

type GetUserStoryResp struct {
	Code     uint   `json:"code"`
	StoryIDs []uint `json:"story_ids"`
}

type GetActiveStoryReq struct {
}

type GetActiveStoryResp struct {
	Code          uint          `json:"code"`
	FriendStroies []FriendStroy `json:"active_stories"`
}

type DeleteStoryReq struct {
	StoryID uint `json:"story_id"`
}

type DeleteStoryResp struct {
	Code uint `json:"code"`
}

type GetStoryInfoByIdRep struct {
	StoryID uint `path:"story_id"`
}

type GetStoryInfoByIdResp struct {
	Code          uint   `json:"code"`
	StoryID       uint   `json:"story_id"`
	StoryMediaURL string `json:"media_url"`
	CreateAt      uint   `json:"create_at"`
}

type FriendStroy struct {
	UserID     uint   `json:"id"`
	Uuid       string `json:"uuid"`
	UserName   string `json:"name"`
	UserAvatar string `json:"avatar"`
	IsSeen     bool   `json:"is_seen"`
	StoriesIDs []uint `json:"stories_ids"`
}
