// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CommonUserInfo struct {
	ID            uint   `json:"id,omitempty"`
	Uuid          string `json:"uuid,omitempty"`
	NickName      string `json:"name,omitempty"`
	Avatar        string `json:"avatar,omitempty"`
	Email         string `json:"email,omitempty"`
	Cover         string `json:"cover,omitempty"`
	StatusMessage string `json:"status"`
}

type FriendInfo struct {
	ID       uint   `json:"id,omitempty"`
	Uuid     string `json:"uuid,omitempty"`
	NickName string `json:"name,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
}

type FriendStroy struct {
	UserId               uint   `json:"id"`
	Uuid                 string `json:"uuid"`
	UserName             string `json:"name"`
	UserAvatar           string `json:"avatar"`
	IsSeen               bool   `json:"is_seen"`
	LatestStoryTimeStamp uint   `json:"latest_story_time_stamp"`
}

type FullGroupInfo struct {
	GroupInfo
	Members   uint   `json:"members"`
	IsJoined  bool   `json:"is_joined"`
	IsOwner   bool   `json:"is_owner"`
	CreatedBy string `json:"created_by"`
}

type GroupInfo struct {
	ID        uint   `json:"id"`
	Uuid      string `json:"uuid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Desc      string `json:"desc"`
	CreatedAt uint   `json:"created_at"`
}

type GroupMemberInfo struct {
	CommonUserInfo
	IsGroupLead bool `json:"is_group_lead"`
}

type MessageUser struct {
	MessageID   uint   `json:"id"`
	FromID      uint   `json:"from_id"`
	ToID        uint   `json:"to_id"`
	Content     string `json:"content"`
	ContentType string `json:"content_type"`
	MessageType uint   `json:"message_type"`
	Url         string `json:"url"`
	FileName    string `json:"file_name"`
	FileSize    uint   `json:"file_size"`
	StoryTime   uint   `json:"story_available_time"`
	CreatedAt   uint   `json:"create_at"`
}

type PageableInfo struct {
	TotalPage uint `json:"total_page"`
	Page      uint `json:"current_page"`
}

type SearchUserResult struct {
	UserInfo CommonUserInfo `json:"user_info"`
	IsFriend bool           `json:"is_friend"`
}

type StickerInfo struct {
	StickerID   string `json:"sticker_id"`
	StickerName string `json:"sticker_name"`
	StickerThum string `json:"sticker_thum"`
}

type StoryInfo struct {
	StoryID       uint   `json:"story_id"`
	StoryUUID     string `json:"story_uuid"`
	StoryMediaURL string `json:"media_url"`
}

type StorySeenInfo struct {
	UserId     uint   `json:"id"`
	Uuid       string `json:"uuid"`
	UserName   string `json:"name"`
	UserAvatar string `json:"avatar"`
	IsLiked    bool   `json:"is_liked"`
	CreatedAt  uint   `json:"created_at"`
}

type StorySeenUserBasicInfo struct {
	Id     uint   `json:"user_id"`
	Avatar string `json:"avatar"`
}

type UploadImagesReq struct {
}

type UploadImagesResp struct {
}

type UploadUserCoverReq struct {
}

type UploadUserCoverResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}
