// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddStickerReq struct {
	StickerUUID string `json:"sticker_id"`
}

type AddStickerResp struct {
	Code uint `json:"code"`
}

type DeleteStickerReq struct {
	StickerUUID string `json:"sticker_id"`
}

type DeleteStickerResp struct {
	Code uint `json:"code"`
}

type GetUserFriendProfileReq struct {
	UserId uint   `form:"id,optional"`
	UUID   string `form:"uuid,optional"`
}

type GetUserFriendProfileResp struct {
	Code     uint           `json:"code"`
	UserInfo CommonUserInfo `json:"user_info"`
	IsFriend bool           `json:"is_friend"`
}

type GetUserInfoReq struct {
	UserId uint   `form:"id,optional"`
	UUID   string `form:"uuid,optional"`
}

type GetUserInfoResp struct {
	Code          uint   `json:"code"`
	UUID          string `json:"uuid"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	Avatar        string `json:"avatar"`
	Cover         string `json:"cover"`
	StatusMessage string `json:"status"`
}

type GetUserStickerReq struct {
}

type GetUserStickerResp struct {
	Code     uint          `json:"code"`
	Stickers []StickerInfo `json:"stickers"`
}

type IsStickerExistReq struct {
	StickerUUID string `path:"sticker_id"`
}

type IsStickerExistResp struct {
	Code    uint `json:"code"`
	IsExist bool `json:"is_exist"`
}

type SearchUserReq struct {
	Qurey string `form:"query"`
}

type SearchUserResp struct {
	Code    uint               `json:"code"`
	Results []SearchUserResult `json:"results"`
}

type SignInReq struct {
	Email    string `json:"email" validate:"email,min=8,max=32"`
	Password string `json:"password" validate:"min=8,max=32"`
}

type SignInResp struct {
	Code        uint           `json:"code"`
	Token       string         `json:"token"`
	ExpiredTime uint           `json:"expired_time"`
	UserInfo    CommonUserInfo `json:"user_info"`
}

type SignUpReq struct {
	Email    string `json:"email" validate:"email,min=8,max=32"`
	Name     string `json:"name" validate:"min=4,max=16"`
	Password string `json:"password" validate:"min=8,max=32"`
}

type SignUpResp struct {
	Code        uint   `json:"code"`
	Token       string `json:"token"`
	ExpiredTime uint   `json:"expired_time"`
}

type UpdateUserInfoReq struct {
	Name string `json:"name" validate:"min=4,max=32"`
}

type UpdateUserInfoResp struct {
	Code uint `json:"code"`
}

type UpdateUserStatusReq struct {
	Status string `json:"status" validate:"max=50"`
}

type UpdateUserStatusResp struct {
	Code uint `json:"code"`
}

type UploadUserAvatarReq struct {
}

type UploadUserAvatarResp struct {
	Code uint   `json:"code"`
	Path string `json:"path"`
}
