// Code generated by goctl. DO NOT EDIT.
// Source: assets.proto

package server

import (
	"api/app/assets/cmd/rpc/internal/logic"
	"api/app/assets/cmd/rpc/internal/svc"
	"api/app/assets/cmd/rpc/types/assets_api"
)

type AssetRPCServer struct {
	svcCtx *svc.ServiceContext
	assets_api.UnimplementedAssetRPCServer
}

func NewAssetRPCServer(svcCtx *svc.ServiceContext) *AssetRPCServer {
	return &AssetRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *AssetRPCServer) UploadImage(stream assets_api.AssetRPC_UploadImageServer) error {
	l := logic.NewUploadImageLogic(stream.Context(), s.svcCtx)
	return l.UploadImage(stream)
}

func (s *AssetRPCServer) UploadFile(stream assets_api.AssetRPC_UploadFileServer) error {
	l := logic.NewUploadFileLogic(stream.Context(), s.svcCtx)
	return l.UploadFile(stream)
}
