// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: socket-proto/socket.proto

package socket_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageID      string                 `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"` // messageID / packageID
	ReplyMessageID string                 `protobuf:"bytes,2,opt,name=replyMessageID,proto3" json:"replyMessageID,omitempty"`
	Avatar         string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`             //user avatar path
	FromUserName   string                 `protobuf:"bytes,4,opt,name=fromUserName,proto3" json:"fromUserName,omitempty"` //sender user name
	FromUUID       string                 `protobuf:"bytes,5,opt,name=fromUUID,proto3" json:"fromUUID,omitempty"`         //sender uuid
	ToUUID         string                 `protobuf:"bytes,6,opt,name=toUUID,proto3" json:"toUUID,omitempty"`             //receiver uuid
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`           //sending content
	ContentType    string                 `protobuf:"bytes,8,opt,name=contentType,proto3" json:"contentType,omitempty"`   //sending content type. For example 1: text, 2: file, 3: audio, 4: video....
	EventType      string                 `protobuf:"bytes,9,opt,name=eventType,proto3" json:"eventType,omitempty"`       //For example: "heatbeat" for checking server/client health , video call/audio call ->"webrtc"
	MessageType    int32                  `protobuf:"varint,10,opt,name=messageType,proto3" json:"messageType,omitempty"` //1: single 2: group
	GroupName      string                 `protobuf:"bytes,11,opt,name=groupName,proto3" json:"groupName,omitempty"`      // will have data iff messageType = 2
	GroupAvatar    string                 `protobuf:"bytes,12,opt,name=groupAvatar,proto3" json:"groupAvatar,omitempty"`  //will have data iff messageType = 2
	// more....
	UrlPath  string `protobuf:"bytes,13,opt,name=urlPath,proto3" json:"urlPath,omitempty"` //file url path or other path
	FileName string `protobuf:"bytes,14,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize int32  `protobuf:"varint,15,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	// will it work on group??
	ContentAvailableTime int32  `protobuf:"varint,16,opt,name=contentAvailableTime,proto3" json:"contentAvailableTime,omitempty"`
	ContentUUID          string `protobuf:"bytes,17,opt,name=contentUUID,proto3" json:"contentUUID,omitempty"`
	ContentUserName      string `protobuf:"bytes,18,opt,name=contentUserName,proto3" json:"contentUserName,omitempty"`
	ContentUserAvatar    string `protobuf:"bytes,19,opt,name=contentUserAvatar,proto3" json:"contentUserAvatar,omitempty"`
	ContentUserUUID      string `protobuf:"bytes,20,opt,name=contentUserUUID,proto3" json:"contentUserUUID,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_socket_proto_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_socket_proto_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_socket_proto_socket_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *Message) GetReplyMessageID() string {
	if x != nil {
		return x.ReplyMessageID
	}
	return ""
}

func (x *Message) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Message) GetFromUserName() string {
	if x != nil {
		return x.FromUserName
	}
	return ""
}

func (x *Message) GetFromUUID() string {
	if x != nil {
		return x.FromUUID
	}
	return ""
}

func (x *Message) GetToUUID() string {
	if x != nil {
		return x.ToUUID
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Message) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *Message) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Message) GetGroupAvatar() string {
	if x != nil {
		return x.GroupAvatar
	}
	return ""
}

func (x *Message) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *Message) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Message) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Message) GetContentAvailableTime() int32 {
	if x != nil {
		return x.ContentAvailableTime
	}
	return 0
}

func (x *Message) GetContentUUID() string {
	if x != nil {
		return x.ContentUUID
	}
	return ""
}

func (x *Message) GetContentUserName() string {
	if x != nil {
		return x.ContentUserName
	}
	return ""
}

func (x *Message) GetContentUserAvatar() string {
	if x != nil {
		return x.ContentUserAvatar
	}
	return ""
}

func (x *Message) GetContentUserUUID() string {
	if x != nil {
		return x.ContentUserUUID
	}
	return ""
}

var File_socket_proto_socket_proto protoreflect.FileDescriptor

const file_socket_proto_socket_proto_rawDesc = "" +
	"\n" +
	"\x19socket-proto/socket.proto\x12\amessage\"\xa5\x05\n" +
	"\aMessage\x12\x1c\n" +
	"\tmessageID\x18\x01 \x01(\tR\tmessageID\x12&\n" +
	"\x0ereplyMessageID\x18\x02 \x01(\tR\x0ereplyMessageID\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\"\n" +
	"\ffromUserName\x18\x04 \x01(\tR\ffromUserName\x12\x1a\n" +
	"\bfromUUID\x18\x05 \x01(\tR\bfromUUID\x12\x16\n" +
	"\x06toUUID\x18\x06 \x01(\tR\x06toUUID\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12 \n" +
	"\vcontentType\x18\b \x01(\tR\vcontentType\x12\x1c\n" +
	"\teventType\x18\t \x01(\tR\teventType\x12 \n" +
	"\vmessageType\x18\n" +
	" \x01(\x05R\vmessageType\x12\x1c\n" +
	"\tgroupName\x18\v \x01(\tR\tgroupName\x12 \n" +
	"\vgroupAvatar\x18\f \x01(\tR\vgroupAvatar\x12\x18\n" +
	"\aurlPath\x18\r \x01(\tR\aurlPath\x12\x1a\n" +
	"\bfileName\x18\x0e \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileSize\x18\x0f \x01(\x05R\bfileSize\x122\n" +
	"\x14contentAvailableTime\x18\x10 \x01(\x05R\x14contentAvailableTime\x12 \n" +
	"\vcontentUUID\x18\x11 \x01(\tR\vcontentUUID\x12(\n" +
	"\x0fcontentUserName\x18\x12 \x01(\tR\x0fcontentUserName\x12,\n" +
	"\x11contentUserAvatar\x18\x13 \x01(\tR\x11contentUserAvatar\x12(\n" +
	"\x0fcontentUserUUID\x18\x14 \x01(\tR\x0fcontentUserUUIDB\x12Z\x10./socket_messageb\x06proto3"

var (
	file_socket_proto_socket_proto_rawDescOnce sync.Once
	file_socket_proto_socket_proto_rawDescData []byte
)

func file_socket_proto_socket_proto_rawDescGZIP() []byte {
	file_socket_proto_socket_proto_rawDescOnce.Do(func() {
		file_socket_proto_socket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socket_proto_socket_proto_rawDesc), len(file_socket_proto_socket_proto_rawDesc)))
	})
	return file_socket_proto_socket_proto_rawDescData
}

var file_socket_proto_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_socket_proto_socket_proto_goTypes = []any{
	(*Message)(nil), // 0: message.Message
}
var file_socket_proto_socket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_socket_proto_socket_proto_init() }
func file_socket_proto_socket_proto_init() {
	if File_socket_proto_socket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_proto_socket_proto_rawDesc), len(file_socket_proto_socket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_proto_socket_proto_goTypes,
		DependencyIndexes: file_socket_proto_socket_proto_depIdxs,
		MessageInfos:      file_socket_proto_socket_proto_msgTypes,
	}.Build()
	File_socket_proto_socket_proto = out.File
	file_socket_proto_socket_proto_goTypes = nil
	file_socket_proto_socket_proto_depIdxs = nil
}
