// Code generated by goctl. DO NOT EDIT.
package types

type CommonUserInfo struct {
	ID            uint   `json:"id,omitempty"`
	Uuid          string `json:"uuid,omitempty"`
	NickName      string `json:"name,omitempty"`
	Avatar        string `json:"avatar,omitempty"`
	Email         string `json:"email,omitempty"`
	Cover         string `json:"cover,omitempty"`
	StatusMessage string `json:"status"`
}

type HealthCheckResp struct {
	Resp string `json:"resp"`
}

type PageableInfo struct {
	TotalPage uint `json:"total_page"`
	Page      uint `json:"current_page"`
}
