// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	assets "github.com/ryantokmanmokmtm/chat-app-server/app/assets/cmd/api/internal/handler/assets"
	health "github.com/ryantokmanmokmtm/chat-app-server/app/assets/cmd/api/internal/handler/health"
	"github.com/ryantokmanmokmtm/chat-app-server/app/assets/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Upload any file
				Method:  http.MethodPost,
				Path:    "/asset/file/upload",
				Handler: assets.UploadFileHandler(serverCtx),
			},
			{
				// Upload image by base64
				Method:  http.MethodPost,
				Path:    "/asset/image/base64/upload",
				Handler: assets.UploadImageByBase64Handler(serverCtx),
			},
			{
				// Upload image by form
				Method:  http.MethodPost,
				Path:    "/asset/image/upload",
				Handler: assets.UploadImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/asset/ping",
				Handler: health.HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
