package variable

// EventType
const (
	HEAT_BEAT_PING = "HEAT_BEAT_PING"
	HEAT_BEAT_PONG = "HEAT_BEAT_PONG"
	SYSTEM         = "SYSTEM"
	MESSAGE        = "MESSAGE"
	WEB_RTC        = "WEB_RTC"
	MSG_ACK        = "MSG_ACK"
	RECALL         = "RECALL"

	//For SFU feature

	//PrducerEvent
	SFU_EVENT_PRODUCER_SDP       = "SFU_EVENT_PRODUCER_SDP"
	SFU_EVENT_PRODUCER_ICE       = "SFU_EVENT_PRODUCER_ICE"
	SFU_EVENT_PRODUCER_CLOSE     = "SFU_EVENT_PRODUCER_CLOSE"
	SFU_EVENT_PRODUCER_CONNECTED = "SFU_EVENT_PRODUCER_CONNECTED"

	SFU_EVENT_CONSUMER_SDP   = "SFU_EVENT_CONSUMER_SDP"
	SFU_EVENT_CONSUMER_ICE   = "SFU_EVENT_CONSUMER_ICE"
	SFU_EVENT_CONSUMER_CLOSE = "SFU_EVENT_CONSUMER_CLOSE"

	//SFU_EVENT_GET_PRODUCERS     = "SFU_EVENT_GET_PRODUCERS"
	SFU_EVENT_SEND_NEW_PRODUCER     = "SFU_EVENT_SEND_NEW_PRODUCER"
	SFU_EVENT_PRODUCER_MEDIA_STATUS = "SFU_EVENT_PRODUCER_MEDIA_STATUS"

	ALL = "ALL" //For multiple communication

)
