// Code generated by goctl. DO NOT EDIT.
// Source: core.proto

package server

import (
	"context"

	"github.com/ryantokmanmokmtm/chat-app-server/app/core/cmd/rpc/internal/logic/chatservice"
	"github.com/ryantokmanmokmtm/chat-app-server/app/core/cmd/rpc/internal/svc"
	"github.com/ryantokmanmokmtm/chat-app-server/app/core/cmd/rpc/types/core"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServiceServer) GetMessages(ctx context.Context, in *core.GetMessagesReq) (*core.GetMessagesResp, error) {
	l := chatservicelogic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *ChatServiceServer) DeleteMessage(ctx context.Context, in *core.DeleteMessageReq) (*core.DeleteMessageResp, error) {
	l := chatservicelogic.NewDeleteMessageLogic(ctx, s.svcCtx)
	return l.DeleteMessage(in)
}
