// Code generated by goctl. DO NOT EDIT.
// Source: core.proto

package userservice

import (
	"context"

	"api/app/core/cmd/rpc/types/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendReq             = core.AddFriendReq
	AddFriendResp            = core.AddFriendResp
	AddStickerReq            = core.AddStickerReq
	AddStickerResp           = core.AddStickerResp
	AddStoryReq              = core.AddStoryReq
	AddStoryResp             = core.AddStoryResp
	CountUserGroupReq        = core.CountUserGroupReq
	CountUserGroupResp       = core.CountUserGroupResp
	CreateGroupReq           = core.CreateGroupReq
	CreateGroupResp          = core.CreateGroupResp
	CreateStickerGroupReq    = core.CreateStickerGroupReq
	CreateStickerGroupResp   = core.CreateStickerGroupResp
	CreateStoryLikeReq       = core.CreateStoryLikeReq
	CreateStoryLikeResp      = core.CreateStoryLikeResp
	DeleteFriendReq          = core.DeleteFriendReq
	DeleteFriendResp         = core.DeleteFriendResp
	DeleteGroupReq           = core.DeleteGroupReq
	DeleteGroupResp          = core.DeleteGroupResp
	DeleteStickerReq         = core.DeleteStickerReq
	DeleteStickerResp        = core.DeleteStickerResp
	DeleteStoryLikeReq       = core.DeleteStoryLikeReq
	DeleteStoryLikeResp      = core.DeleteStoryLikeResp
	DeleteStoryReq           = core.DeleteStoryReq
	DeleteStoryResp          = core.DeleteStoryResp
	FriendInfo               = core.FriendInfo
	FriendStory              = core.FriendStory
	FullGroupInfo            = core.FullGroupInfo
	GetActiveStoryReq        = core.GetActiveStoryReq
	GetActiveStoryResp       = core.GetActiveStoryResp
	GetFriendInfoReq         = core.GetFriendInfoReq
	GetFriendInfoResp        = core.GetFriendInfoResp
	GetFriendListReq         = core.GetFriendListReq
	GetFriendListResp        = core.GetFriendListResp
	GetGroupInfoByUUIDReq    = core.GetGroupInfoByUUIDReq
	GetGroupInfoByUUIDResp   = core.GetGroupInfoByUUIDResp
	GetGroupMembersReq       = core.GetGroupMembersReq
	GetGroupMembersResp      = core.GetGroupMembersResp
	GetStickerInfoReq        = core.GetStickerInfoReq
	GetStickerInfoResp       = core.GetStickerInfoResp
	GetStickerListReq        = core.GetStickerListReq
	GetStickerListResp       = core.GetStickerListResp
	GetStickerResourcesReq   = core.GetStickerResourcesReq
	GetStickerResourcesResp  = core.GetStickerResourcesResp
	GetStoryInfoByIdRep      = core.GetStoryInfoByIdRep
	GetStoryInfoByIdResp     = core.GetStoryInfoByIdResp
	GetStorySeenListReq      = core.GetStorySeenListReq
	GetStorySeenListResp     = core.GetStorySeenListResp
	GetUserFriendProfileReq  = core.GetUserFriendProfileReq
	GetUserFriendProfileResp = core.GetUserFriendProfileResp
	GetUserGroupReq          = core.GetUserGroupReq
	GetUserGroupResp         = core.GetUserGroupResp
	GetUserInfoReq           = core.GetUserInfoReq
	GetUserInfoResp          = core.GetUserInfoResp
	GetUserStickerReq        = core.GetUserStickerReq
	GetUserStickerResp       = core.GetUserStickerResp
	GetUserStoryReq          = core.GetUserStoryReq
	GetUserStoryResp         = core.GetUserStoryResp
	GroupInfo                = core.GroupInfo
	GroupMemberInfo          = core.GroupMemberInfo
	IsStickerExistReq        = core.IsStickerExistReq
	IsStickerExistResp       = core.IsStickerExistResp
	JoinGroupReq             = core.JoinGroupReq
	JoinGroupResp            = core.JoinGroupResp
	LeaveGroupReq            = core.LeaveGroupReq
	LeaveGroupResp           = core.LeaveGroupResp
	PageableInfo             = core.PageableInfo
	SearchGroupReq           = core.SearchGroupReq
	SearchGroupResp          = core.SearchGroupResp
	SearchUserReq            = core.SearchUserReq
	SearchUserResp           = core.SearchUserResp
	SearchUserRespResult     = core.SearchUserRespResult
	SignInReq                = core.SignInReq
	SignInResp               = core.SignInResp
	SignUpReq                = core.SignUpReq
	SignUpResp               = core.SignUpResp
	StickerData              = core.StickerData
	StickerFileMap           = core.StickerFileMap
	StickerInfo              = core.StickerInfo
	StoryInfo                = core.StoryInfo
	StorySeenInfo            = core.StorySeenInfo
	StorySeenUserBasicInfo   = core.StorySeenUserBasicInfo
	UpdateGroupInfoReq       = core.UpdateGroupInfoReq
	UpdateGroupInfoResp      = core.UpdateGroupInfoResp
	UpdateStorySeenReq       = core.UpdateStorySeenReq
	UpdateStorySeenResp      = core.UpdateStorySeenResp
	UpdateUserInfoReq        = core.UpdateUserInfoReq
	UpdateUserInfoResp       = core.UpdateUserInfoResp
	UpdateUserStatusReq      = core.UpdateUserStatusReq
	UpdateUserStatusResp     = core.UpdateUserStatusResp
	UploadGroupAvatarReq     = core.UploadGroupAvatarReq
	UploadGroupAvatarResp    = core.UploadGroupAvatarResp
	UploadUserAvatarReq      = core.UploadUserAvatarReq
	UploadUserAvatarResp     = core.UploadUserAvatarResp
	UploadUserCoverReq       = core.UploadUserCoverReq
	UploadUserCoverResp      = core.UploadUserCoverResp
	UserInfo                 = core.UserInfo

	UserService interface {
		SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpResp, error)
		SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		GetUserFriendProfile(ctx context.Context, in *GetUserFriendProfileReq, opts ...grpc.CallOption) (*GetUserFriendProfileResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error)
		UploadUserAvatar(ctx context.Context, in *UploadUserAvatarReq, opts ...grpc.CallOption) (*UploadUserAvatarResp, error)
		UploadUserCover(ctx context.Context, in *UploadUserCoverReq, opts ...grpc.CallOption) (*UploadUserCoverResp, error)
		SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserResp, error)
		AddUserSticker(ctx context.Context, in *AddStickerReq, opts ...grpc.CallOption) (*AddStickerResp, error)
		DeleteUserSticker(ctx context.Context, in *DeleteStickerReq, opts ...grpc.CallOption) (*DeleteStickerResp, error)
		IsStickerExist(ctx context.Context, in *IsStickerExistReq, opts ...grpc.CallOption) (*IsStickerExistResp, error)
		GetUserStickers(ctx context.Context, in *GetUserStickerReq, opts ...grpc.CallOption) (*GetUserStickerResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.SignUp(ctx, in, opts...)
}

func (m *defaultUserService) SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.SignIn(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) GetUserFriendProfile(ctx context.Context, in *GetUserFriendProfileReq, opts ...grpc.CallOption) (*GetUserFriendProfileResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.GetUserFriendProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusReq, opts ...grpc.CallOption) (*UpdateUserStatusResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

func (m *defaultUserService) UploadUserAvatar(ctx context.Context, in *UploadUserAvatarReq, opts ...grpc.CallOption) (*UploadUserAvatarResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.UploadUserAvatar(ctx, in, opts...)
}

func (m *defaultUserService) UploadUserCover(ctx context.Context, in *UploadUserCoverReq, opts ...grpc.CallOption) (*UploadUserCoverResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.UploadUserCover(ctx, in, opts...)
}

func (m *defaultUserService) SearchUser(ctx context.Context, in *SearchUserReq, opts ...grpc.CallOption) (*SearchUserResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}

func (m *defaultUserService) AddUserSticker(ctx context.Context, in *AddStickerReq, opts ...grpc.CallOption) (*AddStickerResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.AddUserSticker(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUserSticker(ctx context.Context, in *DeleteStickerReq, opts ...grpc.CallOption) (*DeleteStickerResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUserSticker(ctx, in, opts...)
}

func (m *defaultUserService) IsStickerExist(ctx context.Context, in *IsStickerExistReq, opts ...grpc.CallOption) (*IsStickerExistResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.IsStickerExist(ctx, in, opts...)
}

func (m *defaultUserService) GetUserStickers(ctx context.Context, in *GetUserStickerReq, opts ...grpc.CallOption) (*GetUserStickerResp, error) {
	client := core.NewUserServiceClient(m.cli.Conn())
	return client.GetUserStickers(ctx, in, opts...)
}
