package variable

// EventType
const (
	HEAT_BEAT_PING = "HEAT_BEAT_PING"
	HEAT_BEAT_PONG = "HEAT_BEAT_PONG"
	SYSTEM         = "SYSTEM"
	MESSAGE        = "MESSAGE"
	WEB_RTC        = "WEB_RTC"
	MSG_ACK        = "MSG_ACK"
	RECALL         = "RECALL"

	//For SFU feature
	SFU_EVENT_CONNECT       = "SFU_EVENT_CONNECT"
	SFU_EVENT_CONSUM        = "SFU_EVENT_CONSUM"
	SFU_EVENT_GET_PRODUCERS = "SFU_EVENT_GET_PRODUCERS"
	SFU_EVENT_ICE           = "SFU_EVENT_ICE"
	SFU_EVENT_CLOSE         = "SFU_EVENT_CLOSE"

	//Send event -> only use for send to client
	SFU_EVENT_SEND_SDP            = "SFU_EVENT_SEND_SDP"
	SFU_EVENT_SEND_NEW_PRODUCER   = "SFU_EVENT_SEND_NEW_PRODUCER"
	SFU_EVENT_SEND_PRODUCER_CLOSE = "SFU_EVENT_SEND_PRODUCER_CLOSE"
	SFU_EVENT_SEND_CONSUMER_SDP   = "SFU_EVENT_SEND_CONSUMER_SDP"
	ALL                           = "ALL" //For multiple communication

)
