package variable

const (
	SFU_EVENT_SDP            = "SFU_EVENT_SDP"
	SFU_EVENT_ICE            = "SFU_EVENT_ICE"
	SFU_EVENT_PRODUCER       = "SFU_EVENT_PRODUCER"
	SFU_EVENT_NEW_PRODUCER   = "SFU_EVENT_NEW_PRODUCER"
	SFU_EVENT_CLOSE          = "SFU_EVENT_CLOSE"
	SFU_EVENT_PRODUCER_CLOSE = "SFU_EVENT_PRODUCER_CLOSE"
)
